name: noob_example
description: Example app for noob

publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_markdown:
  hooks_riverpod: 
  noob:
    path: ../

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
