name: noob
description: A few handy Flutter tools, dead simple `UriRouter` for `Uri`-based navigator or `BuildTracker`  to track widget rebuilds and what caused them to rebuild.
version: 0.0.7
homepage: https://github.com/derolf/flutter_debug_tools

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  built_collection: ^5.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_test:
    sdk: flutter
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  stack_trace: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^1.1.1
  lint: ^1.5.0
