name: debug_tools
description: A few handy tools to debug Flutter apps.
version: 0.0.1
homepage: https://github.com/derolf/flutter_debug_tools

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  built_collection: ^5.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.14.1
  json_serializable: ^4.1.1
  json_serializable_immutable_collections: ^0.7.0
  lint: ^1.5.3
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: any
  freezed: ^0.14.1
