name: noob
description: A few handy Flutter tools, dead simple `UriRouter` for `Uri`-based navigator or `BuildTracker`  to track widget rebuilds and what caused them to rebuild.
version: 0.0.8
homepage: https://github.com/derolf/flutter_debug_tools

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  built_collection: ^5.1.1
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  stack_trace: ^1.11.0

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
